export { default as ME_QUERY } from './me.gql'
export { default as ME_PESEL_QUERY } from './mePesel.gql'
export { default as ME_RECOMMENDATIONS_QUERY } from './meRecommendations.gql'
export { default as ME_APPOINTMENTS_QUERY } from './meAppointments.gql'
export { default as ME_HISTORIES_QUERY } from './meHistories.gql'
