query(
  $first: Int!
  $after: String
  $note: String
  $date: DateRange!
  $orderBy: [OrderByClause!]
) {
  me {
    id
    appointments(
      first: $first
      after: $after
      note: $note
      date: $date
      orderBy: $orderBy
    ) {
      pageInfo {
        endCursor
        hasNextPage
      }
      edges {
        node {
          id
          date
          note
          confirmed
          author {
            id
            avatar
            name
            phone
          }
          place {
            id
            name
          }
        }
      }
    }
  }
}
