query($page: Int!, $count: Int!) {
  me {
    id
    recommendations(
      page: $page
      count: $count
      is_active: true
      orderBy: [{ field: "start_date", order: ASC }]
    ) {
      paginatorInfo {
        hasMorePages
        currentPage
      }
      data {
        id
        title
        description
        days
        start_date
      }
    }
  }
}
