query(
  $id: ID!
  $first: Int!
  $after: String
  $note: String
  $orderBy: [OrderByClause!]
) {
  user(id: $id) {
    id
    histories(first: $first, after: $after, note: $note, orderBy: $orderBy) {
      pageInfo {
        endCursor
        hasNextPage
      }
      edges {
        node {
          id
          date
          author {
            id
            avatar
            name
            phone
            email
            address
            specialization
          }
          place {
            id
            name
          }
        }
      }
    }
  }
}
