query($id: ID!) {
  place(id: $id) {
    id
    employees {
      id
      permission_type
      is_active
      user {
        id
        avatar
        name
        phone
        email
        address
      }
    }
  }
}
